### ISSUE TITLE
Directory .stellation grows with no pruning of old builds and logs

### ISSUE THREAD

**Issue by Rek-Malorm** [futursolo/stellation#141]
Directory .stellation grows with no pruning of old builds and logs

When actively developing with a live server, a new build is produced for every change. One build for Frontend, one for Backend.
Frontend & Backend directories contain logs and a directory containing serve-builds.

If Autosave is enabled, this directory can quickly bloat with old builds and requires manual clearing. Without clearing, the directory quickly fills the available space until the server crashes.

![image](https://github.com/futursolo/stellation/assets/70321198/662c9e44-3587-4d11-8d20-563e7d3b7896)
![image](https://github.com/futursolo/stellation/assets/70321198/c4997a79-0e70-4184-8972-eb3000be51a7)

**Comment by futursolo** [comment]
I have merged #149, which will be able to remove stale builds for `stctl serve` and `stctl build`.
Existing old builds can be cleaned with `stctl clean`.

I have kept old logs for the moment as it should not be very big.
Logs for `stctl watch` should eventually be printed to stdout and stderr once #4 is solved, which it will no longer be saved to files.
